name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
      security-events: write   # Grants access to dependency graph

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Set up Gradle Validation
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable (Linux only)
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: gradle wrapper && ./gradlew build --no-daemon

      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: Generate Dependency Graph
        run: ./gradlew dependencies --configuration compileClasspath --scan

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4

      - name: Upload JAR file as artifact
        if: ${{ success() }} # Only run this step if the previous steps succeeded
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: build/libs/*.jar